[tools]
python = "3.13"
node = "24"
rust = "1.92.0"
java = "openjdk-25"
"github:rossmacarthur/sheldon" = "latest"
"aqua:starship/starship" = "latest"
"aqua:cli/cli" = "latest"
"aqua:x-motemen/ghq" = "latest"
"gitlab:gitlab-org/cli" = "latest"
"aqua:docker/cli" = "latest"
"aqua:lima-vm/lima" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"vfox:gcloud" = "549.0.1"
"cargo:eza" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:kubernetes-sigs/kind" = "latest"
"aqua:kubernetes-sigs/krew" = "latest"
"aqua:helm/helm" = "latest"
"aqua:argoproj/argo-workflows" = "latest"
"aqua:argoproj/argo-cd" = "latest"
"aqua:astral-sh/uv" = "latest"
"pipx:fabric" = "latest"
"pipx:invoke" = "latest"
"pipx:ansible" = "latest"
"aqua:tfutils/tfenv" = "latest"
"vfox:mise-plugins/vfox-android-sdk" = "latest"

[env]
_.path = [
    "{{env.HOME}}/.krew/bin",
    "{{env.MISE_DATA_DIR}}/installs/vfox-mise-plugins-vfox-android-sdk/latest/platform-tools"
]
